<a href="https://colab.research.google.com/github/Mechanics-Mechatronics-and-Robotics/PytorchBasics/blob/main/02_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Download and install libraries

In [1]:
import torch
import numpy as np

# Scalars, vectors, matrices, and tensors

In [2]:
a = np.array([[1,2,3],[4,5,6]])
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [3]:
x = torch.zeros(2,2)
y = torch.rand(2,2, dtype=torch.float16)
y, y.size(), y.dtype

(tensor([[0.8813, 0.1353],
         [0.7334, 0.5942]], dtype=torch.float16),
 torch.Size([2, 2]),
 torch.float16)

In [4]:
x = torch.tensor([[1,2],[3,4]])
x

tensor([[1, 2],
        [3, 4]])

In [5]:
w = x*y
w

tensor([[0.8813, 0.2705],
        [2.1992, 2.3770]], dtype=torch.float16)

In [6]:
r = w.view(4)
r

tensor([0.8813, 0.2705, 2.1992, 2.3770], dtype=torch.float16)

## Tensor - matrix and matrix - tensor transforms

In [7]:
c = torch.ones(5)
d = c.numpy()
e = torch.from_numpy(d)
c,d,e

(tensor([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1.]))

# Create tensor using GPU (numpy operates with CPU only)

In [8]:
torch.cuda.is_available()

True

In [10]:
if torch.cuda.is_available():
  device = torch.device('cuda')
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y
  z = z.to('cpu')
z

tensor([2., 2., 2., 2., 2.])

## Use gradients

In [11]:
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)