<a href="https://colab.research.google.com/github/Mechanics-Mechatronics-and-Robotics/PytorchBasics/blob/main/02_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Download and Install library

In [2]:
import torch
import numpy as np

# Scalars, vectors, matrices, and tensors

In [3]:
x = torch.empty(2,3)
x

tensor([[5.7670e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

In [4]:
y = torch.rand(2,2, dtype=torch.float16)
y.dtype, y, y.size()

(torch.float16, tensor([[0.5732, 0.8423],
         [0.6309, 0.5884]], dtype=torch.float16), torch.Size([2, 2]))

In [5]:
x = torch.tensor([[1,2],[3,4]])
x

tensor([[1, 2],
        [3, 4]])

In [6]:
z = x + y
z, z[0,0]

(tensor([[1.5732, 2.8418],
         [3.6309, 4.5898]], dtype=torch.float16),
 tensor(1.5732, dtype=torch.float16))

In [7]:
w = x*y
w, w.size()

(tensor([[0.5732, 1.6846],
         [1.8926, 2.3535]], dtype=torch.float16), torch.Size([2, 2]))

In [8]:
r = w.view(4)
r

tensor([0.5732, 1.6846, 1.8926, 2.3535], dtype=torch.float16)

In [9]:
a = torch.ones(5)
b = a.numpy()
c = torch.from_numpy(b)
a, b, c

(tensor([1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1.]))

## Create tensor using GPU (numpy operates with CPU only)

In [11]:
torch.cuda.is_available()

True

In [10]:
if torch.cuda.is_available():
  device = torch.device('cuda')
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y
  z= z.to('cpu')

## Use gradients

In [13]:
x = torch.ones(5,requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)