<a href="https://colab.research.google.com/github/Mechanics-Mechatronics-and-Robotics/PytorchBasics/blob/main/03_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import libraries

In [29]:
import torch

## Use gradients

In [30]:
x = torch.tensor([1,2,3], dtype=torch.float16, requires_grad=True)
x

tensor([1., 2., 3.], dtype=torch.float16, requires_grad=True)

In [31]:
y = x - 1
z = y*y
j = z.mean()
j

tensor(1.6670, dtype=torch.float16, grad_fn=<MeanBackward0>)

In [32]:
j.backward()
x.grad

tensor([0.0000, 0.6665, 1.3330], dtype=torch.float16)

In [33]:
c = x.detach()
c

tensor([1., 2., 3.], dtype=torch.float16)

In [34]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(5):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


tensor([1., 1., 1., 1.], requires_grad=True)


/usr/local/lib/python3.7/dist-packages/torch/optim/sgd.py:105: UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an error; see github.com/pytorch/pytorch/issues/40967 for more information
  super(SGD, self).__init__(params, defaults)
