<a href="https://colab.research.google.com/github/Mechanics-Mechatronics-and-Robotics/PytorchBasics/blob/main/03_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Download and Install library

In [160]:
import torch
import numpy as np

## Use gradients

In [161]:
x = torch.tensor([1, 2, 3],dtype=torch.float16, requires_grad=True)
x

tensor([1., 2., 3.], dtype=torch.float16, requires_grad=True)

In [162]:
y = x - 1
z = y*y*2
z = z.mean()
y, z

(tensor([0., 1., 2.], dtype=torch.float16, grad_fn=<SubBackward0>),
 tensor(3.3340, dtype=torch.float16, grad_fn=<MeanBackward0>))

In [163]:
z.backward()
x.grad

tensor([0.0000, 1.3330, 2.6660], dtype=torch.float16)

In [164]:
#x.requires_grad_(False)
y = x.detach()
with torch.no_grad():
  w = x+2

x,y,w

(tensor([1., 2., 3.], dtype=torch.float16, requires_grad=True),
 tensor([1., 2., 3.], dtype=torch.float16),
 tensor([3., 4., 5.], dtype=torch.float16))

In [167]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()
  


tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [166]:
weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD([weights], lr=0.01)
optimizer.step()
optimizer.zero_grad()
print(weights)

tensor([1., 1., 1., 1.], requires_grad=True)
