<a href="https://colab.research.google.com/github/Mechanics-Mechatronics-and-Robotics/PytorchBasics/blob/main/10_dataset_transforms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import libraries

In [22]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

from google.colab import drive

## Initialization

In [23]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Data set

In [24]:
class WineDataset(Dataset):

  def __init__(self, transform=None):
    #data loading
    xy = np.loadtxt('/content/drive/MyDrive/Colab Notebooks/pytorchTutorial-master/pytorchTutorial-master/data/wine/wine.csv', delimiter=',', dtype=np.float32, skiprows=1)
    self.x = xy[:, 1:]
    self.y = xy[:,[0]] #n
    self.n_samples = xy.shape[0]

    self.transform = transform

  def __getitem__(self, index):
    sample = self.x[index], self.y[index]

    if self.transform:
      sample = self.transform(sample)

    return sample

  def __len__(self):
    return self.n_samples

In [25]:
class ToTensor:
  def __call__(self, sample):
    inputs, targets = sample
    return torch.from_numpy(inputs), torch.from_numpy(targets)
    

In [33]:
class MultTransform:
  def __init__(self,factor):
    self.factor = factor

  def __call__(self, sample):
    inputs, targets = sample
    inputs *= self.factor
    return inputs, targets

In [31]:
dataset = WineDataset(transform=ToTensor())
first_data = dataset[0]
print(first_data)

(tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]), tensor([1.]))


In [34]:
composed = torchvision.transforms.Compose([ToTensor(), MultTransform(2)])
dataset = WineDataset(transform=composed)
first_data = dataset[0]
print(first_data)


(tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
        6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
        2.1300e+03]), tensor([1.]))


In [35]:
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True, num_workers=2)

In [36]:
dataiter = iter(dataloader)
data = dataiter.next()
features, labels = data
features, labels

(tensor([[2.3920e+01, 2.1800e+00, 4.6000e+00, 4.2000e+01, 2.0200e+02, 6.7600e+00,
          4.2800e+00, 2.6000e-01, 3.3000e+00, 6.4200e+00, 1.9800e+00, 6.2600e+00,
          1.7720e+03],
         [2.7260e+01, 3.6200e+00, 5.4000e+00, 3.4400e+01, 2.2400e+02, 5.7000e+00,
          5.8200e+00, 6.0000e-01, 2.9200e+00, 1.4600e+01, 2.5600e+00, 5.7600e+00,
          2.6200e+03],
         [2.4160e+01, 2.2600e+00, 5.0200e+00, 4.8000e+01, 1.5600e+02, 4.0000e+00,
          3.1600e+00, 8.0000e-01, 2.8000e+00, 4.4000e+00, 2.6200e+00, 5.4400e+00,
          1.2600e+03],
         [2.5020e+01, 2.4800e+00, 4.5000e+00, 3.5000e+01, 1.7000e+02, 4.0000e+00,
          1.1600e+00, 1.2000e+00, 2.5000e+00, 1.0900e+01, 1.5000e+00, 3.0200e+00,
          1.3000e+03]]), tensor([[2.],
         [1.],
         [2.],
         [3.]]))

In [29]:
#training loop
num_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4)
total_samples, n_iterations

for epoch in range(num_epochs):
  for i, (inputs, labels) in enumerate (dataloader):
    # forward, backward
    if (i+1) % 5 == 0:
      print(f'epoch {epoch+1}/{num_epochs}, step {i+1}/{n_iterations}, inputs {inputs.shape}')

epoch 1/2, step 5/45, inputs torch.Size([4, 13])
epoch 1/2, step 10/45, inputs torch.Size([4, 13])
epoch 1/2, step 15/45, inputs torch.Size([4, 13])
epoch 1/2, step 20/45, inputs torch.Size([4, 13])
epoch 1/2, step 25/45, inputs torch.Size([4, 13])
epoch 1/2, step 30/45, inputs torch.Size([4, 13])
epoch 1/2, step 35/45, inputs torch.Size([4, 13])
epoch 1/2, step 40/45, inputs torch.Size([4, 13])
epoch 1/2, step 45/45, inputs torch.Size([2, 13])
epoch 2/2, step 5/45, inputs torch.Size([4, 13])
epoch 2/2, step 10/45, inputs torch.Size([4, 13])
epoch 2/2, step 15/45, inputs torch.Size([4, 13])
epoch 2/2, step 20/45, inputs torch.Size([4, 13])
epoch 2/2, step 25/45, inputs torch.Size([4, 13])
epoch 2/2, step 30/45, inputs torch.Size([4, 13])
epoch 2/2, step 35/45, inputs torch.Size([4, 13])
epoch 2/2, step 40/45, inputs torch.Size([4, 13])
epoch 2/2, step 45/45, inputs torch.Size([2, 13])
